"""
The signing procedure, defined once for the whole Python side.

    strip `signature` -> RFC 8785 JCS -> Ed25519 -> base64url unpadded

Lane B imports from here rather than reimplementing. Lane C's browser
implementation is independent and is held to byte equality against
`fixtures/keys/test_vector.json`, which is generated by
`scripts/gen_test_vector.py`.

If you change anything in this module, regenerate the vector and run the
console's parity test before you commit. A silent canonicalisation change is
the kind of bug that only shows up on stage.
"""

from __future__ import annotations

import base64
from typing import Any, Mapping

from cryptography.hazmat.primitives.asymmetric.ed25519 import (
    Ed25519PrivateKey,
    Ed25519PublicKey,
)

from contracts.jcs import canonicalize

SIGNATURE_FIELD = "signature"


# --------------------------------------------------------------- base64url ---


def b64u_encode(raw: bytes) -> str:
    return base64.urlsafe_b64encode(raw).decode("ascii").rstrip("=")


def b64u_decode(s: str) -> bytes:
    # Python's decoder demands padding; the wire format does not carry it.
    return base64.urlsafe_b64decode(s + "=" * (-len(s) % 4))


# ------------------------------------------------------------------- keys ---


def generate_keypair() -> tuple[Ed25519PrivateKey, str]:
    """Returns the private key and its base64url public key."""
    priv = Ed25519PrivateKey.generate()
    return priv, b64u_encode(priv.public_key().public_bytes_raw())


def private_key_from_seed(seed: bytes) -> Ed25519PrivateKey:
    return Ed25519PrivateKey.from_private_bytes(seed)


def public_key_from_b64u(pubkey_b64u: str) -> Ed25519PublicKey:
    """Raises ValueError on anything that is not a 32 byte Ed25519 key."""
    raw = b64u_decode(pubkey_b64u)
    if len(raw) != 32:
        raise ValueError(f"Ed25519 public key must be 32 bytes, got {len(raw)}")
    return Ed25519PublicKey.from_public_bytes(raw)


# ---------------------------------------------------------------- signing ---


def signing_bytes(payload: Mapping[str, Any]) -> bytes:
    """The exact bytes that get signed. Exposed so tests can assert on them."""
    unsigned = {k: v for k, v in payload.items() if k != SIGNATURE_FIELD}
    return canonicalize(unsigned)


def sign(payload: Mapping[str, Any], private_key: Ed25519PrivateKey) -> str:
    return b64u_encode(private_key.sign(signing_bytes(payload)))


def verify(payload: Mapping[str, Any], signature_b64u: str, pubkey_b64u: str) -> bool:
    """
    True only if the signature verifies. Every failure mode — malformed key,
    malformed signature, wrong length, bad base64 — returns False rather than
    raising, because a verification helper that raises on hostile input is a
    denial of service in the request path.

    Fail closed: this returns False, and the caller turns False into BLOCK.
    """
    try:
        public_key_from_b64u(pubkey_b64u).verify(
            b64u_decode(signature_b64u), signing_bytes(payload)
        )
        return True
    except Exception:
        # Deliberately broad. InvalidSignature is the expected failure, but
        # malformed base64, a wrong-length key and a non-string input all reach
        # here too, and every one of them means "not verified".
        return False
